In [87]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [88]:
import pandas as pd

In [85]:
bookings=pd.read_csv("hotel_bookings_50.csv")
bookings.head(5)

,booking_id,customer_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,...,is_repeated_guest,reserved_room_type,assigned_room_type,deposit_type,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,1,1,City Hotel,0,62,2024,April,1,0,1,...,0,C,D,Refundable,Contract,206.09,1,1,Check-Out,01-01-2026
1,2,2,City Hotel,1,216,2024,July,2,2,0,...,1,B,C,Non Refund,Transient,281.70,2,2,No-Show,02-01-2026
2,3,3,City Hotel,0,293,2024,November,1,1,0,...,1,E,E,Non Refund,Transient,206.05,2,3,Canceled,03-01-2026
3,4,4,Resort Hotel,0,99,2026,August,2,2,1,...,0,E,D,No Deposit,Transient,305.65,0,2,Check-Out,04-01-2026
4,5,5,City Hotel,0,172,2025,November,1,2,1,...,0,C,C,Non Refund,Transient-Party,215.57,0,2,Check-Out,05-01-2026

In [75]:
cust=pd.read_csv("customers.csv")
cust.head(5)

   customer_id    customer_name                      email country
0            1     Aarav Sharma     aarav.sharma@gmail.com   India
1            2     Ananya Patel     ananya.patel@gmail.com   India
2            3      Rohan Mehta      rohan.mehta@gmail.com   India
3            4      Priya Desai      priya.desai@gmail.com   India
4            5  Aditya Kulkarni  aditya.kulkarni@gmail.com   India

In [76]:
len(bookings)

50

In [77]:
len(cust)

50

In [78]:
bookings.columns

Index(['booking_id', 'customer_id', 'hotel', 'is_canceled', 'lead_time',
       'arrival_date_year', 'arrival_date_month', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'reservation_status',
       'reservation_status_date'],
      dtype='object')

In [79]:
cust.columns

Index(['customer_id', 'customer_name', 'email', 'country'], dtype='object')

In [54]:
bookings.tail()

,booking_id,customer_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,...,is_repeated_guest,reserved_room_type,assigned_room_type,deposit_type,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
45,46,46,Resort Hotel,0,44,2025,March,2,1,0,...,1,A,A,Non Refund,Contract,153.70,2,3,Canceled,15-02-2026
46,47,47,City Hotel,0,286,2024,July,2,1,1,...,0,A,A,Refundable,Group,319.04,1,2,Check-Out,16-02-2026
47,48,48,Resort Hotel,1,128,2025,December,2,2,0,...,0,E,E,No Deposit,Contract,192.19,1,1,Canceled,17-02-2026
48,49,49,City Hotel,0,231,2025,October,2,1,0,...,1,D,C,Non Refund,Transient-Party,250.27,0,1,No-Show,18-02-2026
49,50,50,City Hotel,0,190,2026,September,2,2,1,...,1,D,A,Refundable,Transient-Party,101.70,1,2,No-Show,19-02-2026

In [55]:
cust.tail()

    customer_id  customer_name                    email  country
45           46   Anna Schmidt   anna.schmidt@gmail.com  Germany
46           47    Jean Martin    jean.martin@gmail.com   France
47           48  Claire Dubois  claire.dubois@gmail.com   France
48           49    Marco Rossi    marco.rossi@gmail.com    Italy
49           50  Giulia Romano  giulia.romano@gmail.com    Italy

In [56]:
bookings.shape

(50, 23)

In [57]:
cust.shape

(50, 4)

In [58]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   booking_id                   50 non-null     int64
 1   customer_id                  50 non-null     int64
 2   hotel                        50 non-null     object
 3   is_canceled                  50 non-null     int64
 4   lead_time                    50 non-null     int64
 5   arrival_date_year            50 non-null     int64
 6   arrival_date_month           50 non-null     object
 7   adults                       50 non-null     int64
 8   children                     50 non-null     int64
 9   babies                       50 non-null     int64
 10  meal                         50 non-null     object
 11  market_segment               50 non-null     object
 12  distribution_channel         50 non-null     object
 13  is_repeated_guest            50 non-null     int64
 14  reserved_room_type           50 non-null     object
 15  assigned_room_type           50 non-null     object
 16  deposit_type                 50 non-null     object
 17  customer_type                50 non-null     object
 18  adr                          50 non-null     float64
 19  required_car_parking_spaces  50 non-null     int64
 20  total_of_special_requests    50 non-null     int64
 21  reservation_status           50 non-null     object
 22  reservation_status_date      50 non-null     object
dtypes: float64(1), int64(11), object(11)
memory usage: 9.1+ KB

In [59]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    50 non-null     int64
 1   customer_name  50 non-null     object
 2   email          50 non-null     object
 3   country        50 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.7+ KB

In [60]:
#---------------------
# Cleaning
#---------------------

In [61]:
bookings.isnull().sum()

booking_id                     0
customer_id                    0
hotel                          0
is_canceled                    0
lead_time                      0
arrival_date_year              0
arrival_date_month             0
adults                         0
children                       0
babies                         0
meal                           0
market_segment                 0
distribution_channel           0
is_repeated_guest              0
reserved_room_type             0
assigned_room_type             0
deposit_type                   0
customer_type                  0
adr                            0
required_car_parking_spaces    0
total_of_special_requests      0
reservation_status             0
reservation_status_date        0
dtype: int64

In [62]:
cust.isnull().sum()

customer_id      0
customer_name    0
email            0
country          0
dtype: int64

In [65]:
bookings.duplicated().sum()

np.int64(0)

In [66]:
cust.duplicated().sum()

np.int64(0)

In [67]:
# hotel.drop_duplicates()
# cust.drop_duplicates()

In [68]:
bookings.dtypes

booking_id                       int64
customer_id                      int64
hotel                           object
is_canceled                      int64
lead_time                        int64
arrival_date_year                int64
arrival_date_month              object
adults                           int64
children                         int64
babies                           int64
meal                            object
market_segment                  object
distribution_channel            object
is_repeated_guest                int64
reserved_room_type              object
assigned_room_type              object
deposit_type                    object
customer_type                   object
adr                            float64
required_car_parking_spaces      int64
total_of_special_requests        int64
reservation_status              object
reservation_status_date         object
dtype: object

In [69]:
cust.dtypes

customer_id       int64
customer_name    object
email            object
country          object
dtype: object

In [70]:
import  numpy as np

In [71]:
adr=np.array(bookings["adr"])

In [89]:
np.min(adr)

np.float64(54.36)

In [26]:
np.sum(adr)

np.float64(9632.68)

In [27]:
np.max(adr)

np.float64(344.01)

In [28]:
np.median(adr)

np.float64(194.91)

In [29]:
# Booking analysis

In [30]:
len(bookings)

50

In [31]:
bookings['hotel'].value_counts()

hotel
City Hotel      36
Resort Hotel    14
Name: count, dtype: int64

In [32]:
bookings['is_canceled'].value_counts()

is_canceled
0    36
1    14
Name: count, dtype: int64

In [33]:
# hotel wise adr
bookings.groupby("hotel")["adr"].mean()

hotel
City Hotel      207.552222
Resort Hotel    154.342857
Name: adr, dtype: float64

In [34]:
# meal analysis
bookings['meal'].value_counts()

meal
HB    15
SC    15
FB    11
BB     9
Name: count, dtype: int64

In [35]:
bookings['customer_type'].value_counts()

customer_type
Transient          21
Contract           11
Transient-Party    11
Group               7
Name: count, dtype: int64

In [36]:
bookings['reservation_status'].value_counts()

reservation_status
Canceled     20
No-Show      17
Check-Out    13
Name: count, dtype: int64

In [37]:
bookings['arrival_date_month'].value_counts()

arrival_date_month
April        6
November     6
July         5
September    5
March        5
August       4
January      4
June         4
December     4
February     3
October      3
May          1
Name: count, dtype: int64

In [38]:
# customer analysis

In [39]:
customer_bookings=pd.merge(bookings,cust,on="customer_id",how="left")
customer_bookings.head()

,booking_id,customer_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,...,deposit_type,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,customer_name,email,country
0,1,1,City Hotel,0,62,2024,April,1,0,1,...,Refundable,Contract,206.09,1,1,Check-Out,01-01-2026,Aarav Sharma,aarav.sharma@gmail.com,India
1,2,2,City Hotel,1,216,2024,July,2,2,0,...,Non Refund,Transient,281.70,2,2,No-Show,02-01-2026,Ananya Patel,ananya.patel@gmail.com,India
2,3,3,City Hotel,0,293,2024,November,1,1,0,...,Non Refund,Transient,206.05,2,3,Canceled,03-01-2026,Rohan Mehta,rohan.mehta@gmail.com,India
3,4,4,Resort Hotel,0,99,2026,August,2,2,1,...,No Deposit,Transient,305.65,0,2,Check-Out,04-01-2026,Priya Desai,priya.desai@gmail.com,India
4,5,5,City Hotel,0,172,2025,November,1,2,1,...,Non Refund,Transient-Party,215.57,0,2,Check-Out,05-01-2026,Aditya Kulkarni,aditya.kulkarni@gmail.com,India

In [40]:
# country wise average adr 
customer_bookings.groupby("country")["adr"].mean().sort_values(ascending=False)

country
Spain             260.46000
France            255.61500
United States     226.79800
Japan             210.92800
India             193.70125
United Kingdom    182.76750
Italy             175.98500
Brazil            166.95500
Canada            134.42200
Germany           129.13000
Egypt              91.99000
Name: adr, dtype: float64

In [41]:
# booking status
import numpy as np
bookings["bookings_status"]=np.where(bookings["is_canceled"]==1,"Confirmed","Cancelled")
bookings.head()

,booking_id,customer_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,...,reserved_room_type,assigned_room_type,deposit_type,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,bookings_status
0,1,1,City Hotel,0,62,2024,April,1,0,1,...,C,D,Refundable,Contract,206.09,1,1,Check-Out,01-01-2026,Cancelled
1,2,2,City Hotel,1,216,2024,July,2,2,0,...,B,C,Non Refund,Transient,281.70,2,2,No-Show,02-01-2026,Confirmed
2,3,3,City Hotel,0,293,2024,November,1,1,0,...,E,E,Non Refund,Transient,206.05,2,3,Canceled,03-01-2026,Cancelled
3,4,4,Resort Hotel,0,99,2026,August,2,2,1,...,E,D,No Deposit,Transient,305.65,0,2,Check-Out,04-01-2026,Cancelled
4,5,5,City Hotel,0,172,2025,November,1,2,1,...,C,C,Non Refund,Transient-Party,215.57,0,2,Check-Out,05-01-2026,Cancelled

In [42]:
hotel_analysis = (
    bookings.groupby("hotel")
    .agg(
        total_bookings=("booking_id", "count"),
        average_adr=("adr", "mean"),
        
        cancellation_rate=("is_canceled", "mean")
    )
)

hotel_analysis

              total_bookings  average_adr  cancellation_rate
hotel
City Hotel                36   207.552222           0.250000
Resort Hotel              14   154.342857           0.357143

In [43]:
customer_analysis=(
    bookings.groupby("customer_type")
    .agg(
        bookings=("booking_id","count"),
        average_adr=("adr","mean"),
        
    )
)
customer_analysis

                 bookings  average_adr
customer_type
Contract               11   208.696364
Group                   7   160.470000
Transient              21   189.122381
Transient-Party        11   203.832727

In [44]:
bookings.to_csv('booking.csv',index=False)

In [45]:
cust.to_csv('customers.csv',index=False)

In [73]:
final_df = bookings.merge(cust,on='customer_id',how='left')

In [74]:
final_df.to_excel('hotel_booking_final.xlsx',index=False)